const SUPABASE_URL = 'https://abllpxqkyqebtawzwtrd.supabase.co';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFibGxweHFreXFlYnRhd3p3dHJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODEyOTc4NTYsImV4cCI6MjA5Njg3Mzg1Nn0.5mEXCmxz2-QBSGuL3dodLNOesVTivAexo9yUIkihmVc';
const _supabase = supabase.createClient(SUPABASE_URL, SUPABASE_KEY);

const CHALLENGES = [
  { day:  1, icon:'🌸', title:'Shukrona',      desc:'Bugun hayotingda 3 ta yaxshi narsani yoz' },
  { day:  2, icon:'💧', title:'Suv',            desc:'Kamida 8 stakan suv ich' },
  { day:  3, icon:'🧘', title:'Meditatsiya',    desc:'10 daqiqa jim o\'tir, faqat nafas ol' },
  { day:  4, icon:'📚', title:'Kitob',          desc:'20 daqiqa kitob o\'qi' },
  { day:  5, icon:'🌿', title:'Sayr',           desc:'15 daqiqa tashqarida sayr qil' },
  { day:  6, icon:'📵', title:'Detox',          desc:'1 soat telefonsiz o\'tir' },
  { day:  7, icon:'🍳', title:'Yangi taom',     desc:'Yangi retsept bo\'yicha taom pishir' },
  { day:  8, icon:'💌', title:'Do\'st',          desc:'Uzoq ko\'rmagan do\'stingga xabar yoz' },
  { day:  9, icon:'✍️', title:'Yangi so\'z',    desc:'Yangi so\'z o\'rgan va kunida ishlatib ko\'r' },
  { day: 10, icon:'📋', title:'Reja',           desc:'Ertangi kunning rejasini yoz' },
  { day: 11, icon:'💝', title:'O\'zingni sev',  desc:'5 ta yaxshi fazilatingni yoz' },
  { day: 12, icon:'🧹', title:'Tartib',         desc:'Xonangning bir burchagini tartibga keltir' },
  { day: 13, icon:'🎨', title:'Ijod',           desc:'Rasm chiz, qo\'shiq ayt yoki she\'r yoz' },
  { day: 14, icon:'🤝', title:'Yaxshilik',      desc:'Birovga kutilmagan yaxshilik qil' },
  { day: 15, icon:'🎉', title:'Yarim yo\'l!',   desc:'15 kun o\'tdi — o\'zingni tabriklash vaqti' },
  { day: 16, icon:'🌅', title:'Erta tur',       desc:'Odatdagidan 30 daqiqa ertaroq tur' },
  { day: 17, icon:'🏃', title:'Harakat',        desc:'15 daqiqa jismoniy faoliyat: yugur, raqs, o\'yna' },
  { day: 18, icon:'🔍', title:'Yangi janr',     desc:'Hech o\'qimagan janrdagi kitob tanlap ko\'r' },
  { day: 19, icon:'🎙️', title:'Podcast',       desc:'Rivojlanish haqidagi podcast tinglang' },
  { day: 20, icon:'🌟', title:'Maqsad',         desc:'1 oylik maqsadingni yoz va tasavvur qil' },
  { day: 21, icon:'🥗', title:'Sog\'lom ovqat', desc:'Bugun faqat uyda tayyorlangan taom ye' },
  { day: 22, icon:'💡', title:'Yangi mahorat',  desc:'YouTube dan yangi bir narsa o\'rgan' },
  { day: 23, icon:'📓', title:'Jurnal',         desc:'Bugungi his-tuyg\'ularingni batafsil yoz' },
  { day: 24, icon:'✨', title:'Ilhom',          desc:'Seni ilhomlantirgan odamga maqtov yoz' },
  { day: 25, icon:'☀️', title:'Tabiat',         desc:'30 daqiqa tashqarida o\'tir, osmonga qara' },
  { day: 26, icon:'🎵', title:'Musiqa',         desc:'Sevimli qo\'shig\'ingga to\'liq quloq sol' },
  { day: 27, icon:'🕊️', title:'Kechirish',     desc:'Birovni yoki o\'zingni yurakdan kechir' },
  { day: 28, icon:'🌷', title:'Yordam',         desc:'Oila yoki do\'stingga kutilmagan joyda yordam ber' },
  { day: 29, icon:'📷', title:'Xotira',         desc:'Eng baxtli xotirangni yoz yoki rasmga ol' },
  { day: 30, icon:'🏆', title:'BARAKALLA!',     desc:'30 kunlik challengeni yakladingiz! Siz ajoyibsiz 🌸' },
];

const INSP_POOL = {
  happy: {
    self: [
      { e:'🌸', t:'Bugun sen porlab turibsan — bu yorug\'lik ichingdan chiqyapti. O\'zingni shu holatingda sevib, bu lahzani to\'liq his qil. Hech kimga o\'xshash bo\'lishga hojat yo\'q — sen o\'zingcha mukammalsiz.', p:'Bugun o\'zing haqingda eng yoqtirgan 3 narsani yoz.' },
      { e:'💫', t:'Baxtli bo\'lish — bu senga loyiq, va sen uni bugun his qilyapsan. Bu his haqiqiy va senga tegishli. O\'zingni tabriklash — bu xudbin emas, bu sog\'lom.', p:'"Bugun men o\'zimni ... his qilayapman, chunki..." — deb davom ettir.' },
      { e:'🦋', t:'Sen har kuni eng yaxshi versiyangga aylanyapsan — va bugun shu yo\'ldasan. Kapalak qanday chiroyli o\'zgarsa, sen ham o\'shanaqa o\'sib boryapsan. Bu o\'sish sezilinmas, lekin haqiqiy.', p:'Bir yil oldingi o\'zingdan qanday farq qilasiz?' },
      { e:'🌺', t:'Kichik narsalarda baxt topish — bu hayotning eng katta siri, va sen uni egallagan odamsan. Bugun atrofingdagi oddiy go\'zalliklarni ko\'r — ular hamma vaqt shu yerda edi.', p:'Bugun eng kichik lekin eng sevimli narsangni yoz.' },
      { e:'☀️', t:'Sen bugun quyoshdek nur taratayapsan — bu nur atrofingizdagilarga ham yetib boradi. Odamlar sening tabassumingni sezadi, hatto aytmasalar ham. Sen dunyo uchun sovg\'asan.', p:'Bugun kim sizning tabassumingizga ehtiyoj sezadi?' },
      { e:'🍀', t:'Baxtli kunlar — xotira bo\'lib qoladi. Shu lahzani yaxshilab his qil, miyangga yozib qo\'y. Qiyin kunlarda aynan shu xotira senga kuch beradi.', p:'Bu baxtni qanday uzoqroq saqlab qolish mumkin?' },
      { e:'🌈', t:'Sen bugun go\'zal ekanligingni his qilyapsan — bu haqiqat. Tashqi ko\'rinish emas, ichki nur — u bugun ayniqsa yorqin. Atrofingizdagilar ham buni sezmoqda.', p:'"Men kimman?" — bunga bugun qanday javob berasiz?' },
      { e:'💎', t:'Sen qimmatbaho toshsan — lekin uni faqat o\'zing bilasang. Bugun o\'z qadringni his qil. Boshqalarning fikri — ularning proyeksiyasi, haqiqat emas.', p:'O\'z qadr-qimmatini qayerdan olyapsan?' },
      { e:'🌻', t:'Quyoshga qarab o\'sadigon gul kabi sen ham yorug\'lik tomonga intilayapsan. Bu intilish — eng tabiiy narsa. Bugun o\'zingga ruxsat ber — to\'liq ochilishga.', p:'Hozir hayotingda nima seni ilhomlantiryapti?' },
      { e:'✨', t:'Baxtning eng yaxshi tomoni — u ichingdan chiqadi, tashqaridan kelmaydi. Bugun shu ichki manbani topgansan. U hamma vaqt shu yerda bo\'lgan — faqat hozir uni sezayapsan.', p:'Bu baxtning manbasini qanday ta\'riflar edingiz?' },
      { e:'🎀', t:'O\'zingni sevish — bu hayotdagi eng muhim munosabat. Bugun shu munosabat gullab-yashnamoqda. Seni bilgan hamma bu sening yangi yorug\'ligingni sezmoqda.', p:'O\'zingni sevish deb qanday narsani tushunasiz?' },
      { e:'🌷', t:'Sen bugun eng go\'zal holatingdasiz — va bu rasm doim o\'zgarib boradi, lekin har gal go\'zal bo\'ladi. O\'sish — bu eng chiroyli jarayon, va sen uning ichidasan.', p:'O\'sish deb qanday narsani his qilasiz?' },
    ],
    goals: [
      { e:'🚀', t:'Baxtli paytlarda energiya ko\'payadi — ayni shu qadam qo\'yish vaqti! Katta maqsadlar ham bitta kichik harakatdan boshlanadi. Hozir shu harakatni qil.', p:'Bugun eng muhim maqsadingga qanday bitta qadam qo\'ya olasiz?' },
      { e:'🌟', t:'Orzularingni hozir ko\'z oldingga keltir — ular shuncha uzoq emas. Baxtli kayfiyat — maqsadga eng yaxshi ko\'prik. Bugun bitta konkret qadam yoz va boshlash vaqtini belgilab qo\'y.', p:'"5 yildan keyin qanday hayot istayapman?" — detallar bilan yoz.' },
      { e:'🎯', t:'Sen bugun quvonchda ekansan — bu tasodif emas, bu sening to\'g\'ri yo\'ldaganligingning belgisi. Maqsadlaring seni kutmoqda, va sen ularga asta-sekin yaqinlashmoqdasiz.', p:'Hozirgi maqsadingga qancha yaqinlashganingni baholab ko\'r (1-10).' },
      { e:'💡', t:'Baxtli vaqtlarda yangi g\'oyalar to\'lqin kabi keladi. Ularni yozib ol — hamma birini! Keyinchalik ular qimmatga tushishi mumkin. Bugun g\'oyalar ro\'yxatini tuzib qo\'y.', p:'Hozir miyangizda qanday yangi g\'oya bor?' },
      { e:'🏆', t:'Katta natijalar baxtli kunlarda boshlanadi — ayni shu vaqt. O\'zingga katta maqsad qo\'y, qo\'rqmasdan. Agar muvaffaqiyat kafolatlangan bo\'lsa nima qilardingiz?', p:'Hayotdagi eng katta orzuyingizni hech bir cheklovsiz yozing.' },
      { e:'🌱', t:'Bugungi baxt — ertangi maqsad uchun tuproq. Uni yaxshilab tayyorla. Energiyangni hozir to\'g\'ri ishga sarfla — bir yildan keyin minnatdor bo\'lasiz.', p:'Bu baxtni maqsadingga qanday yo\'nalta olasiz?' },
      { e:'⚡', t:'Quvonch — eng yaxshi motivatsiya. Siz bugun kuchli va tayyor ekanmisiz — demak hech narsa to\'sqinlik qilmaydi. Bitta muhim qaror qabul qil va bugun boshla.', p:'Qaysi qarorni eng ko\'p kechiktirayapsiz?' },
      { e:'🎨', t:'Maqsadlarga borish yo\'li ko\'p — va siz o\'zingizga yoqadigan yo\'lni tanlay olasiz. Hozir eng ko\'p ilhomlantiruvchi yo\'lni top. Qiyinchilik bilan emas, quvonch bilan boring.', p:'Maqsadingga qanday qilib zavq bilan borishingiz mumkin?' },
      { e:'🌺', t:'Baxtli ekanligingda maqsadlarga qarash — ularni ulkanroq ko\'rsatadi. Hozir ko\'z oldingga keltir: muvaffaqiyatga erishgandagi o\'zing. U qanday his qilyapti?', p:'Maqsadingga erishganingizda birinchi nima qilasiz?' },
      { e:'🦋', t:'Har bir katta natija kichik qadamlardan iborat — bugun shular ichidan birini qil. Kapalak qanot qoqishini to\'xtatmasa uchadi — sen ham to\'xtama.', p:'Bugun qaysi kichik qadamni qo\'yasiz?' },
      { e:'💫', t:'Siz allaqachon ko\'p narsaga erishdingiz — ammo bundan ham kattalariga erishish mumkin. Bugungi baxtni — maqsadingga erishgandagi baxtning tatib ko\'rishi deb bil.', p:'O\'tgan yildagi eng katta yutuqingiz nima edi?' },
      { e:'🌈', t:'Orzular — faqat ko\'rinadigan narsalar emas, his qilinadigan narsalar ham. Bugun o\'sha hisni his qilyapsizmi? Demak siz to\'g\'ri tomonga ketyapsiz.', p:'Maqsadingiz haqida o\'ylaganda qanday his qilasiz?' },
    ],
    hard: [
      { e:'💪', t:'Quvonchingizda ham o\'tgan qiyinchiliklar yashiringan — ular sizni shu yerga olib keldi. Bugungi baxt — o\'sha qiyinchiliklarning in\'omi. Uni layoqatli odamlar oladi.', p:'Qaysi qiyinchilik sizni eng ko\'p kuchaytirdi?' },
      { e:'🌈', t:'Yomg\'irdan keyin kamalak chiqadi — bugun sen o\'sha kamalaksan. Sening o\'tgan qiyinchiliklaringdan o\'tgan yo\'l — boshqalarga ham ilhom bo\'lishi mumkin.', p:'O\'z hayot yo\'lingizni qanday ta\'riflar edingiz?' },
      { e:'✨', t:'Baxtning qadri — qiyinchilikni bilgan odamga katta. Sen ikkalasini bilasan — bu seni chuqurroq va kuchliroq qiladi. Shu chuqurlikni his qil.', p:'Bugun nimadan minnatdorsiz? 5 ta yozing.' },
      { e:'🌺', t:'Qiyin kunlar o\'tdi — va siz o\'tdingiz. Bu kuch hamma vaqt sizda edi. Bugun o\'sha kuchni tan oling va o\'zingizga rahmat ayting.', p:'O\'zingizga "bardosh berganing uchun rahmat" deb yozing.' },
      { e:'🦁', t:'Siz qiyinchiliklar ichidan chiqqan odamsiz — bu sizni oddiy insondan farqlantiradi. Bu tajriba — oltin. Hozirgi baxtingiz shu oltin uchun mukofot.', p:'Qiyin davrdan qanday kuch oldingiz?' },
      { e:'🌻', t:'Quyosh qanchalik uzoq bo\'lmasin, u oxir-oqibat chiqadi. Siz buni bilasiz — chunki qorong\'u kunlarni ham ko\'rgansiz. Shu bilim — ulkan boylik.', p:'Eng qorong\'u davrda sizga nima yordam berdi?' },
      { e:'💎', t:'Olmoslar faqat bosim ostida yaratiladi. Siz ham qiyinchiliklar ostida shakllanib, endi porlamoqdasiz. Bugungi baxt — o\'sha jarayonning natijasi.', p:'Qiyinchilik sizni qanday shakllantirgani haqida yozing.' },
      { e:'🌊', t:'Dengiz to\'lqinlari qanchalik kuchli bo\'lmasin, qirg\'oq doim turadi. Siz — qirg\'oqsiz. To\'lqinlar o\'tdi, siz qoldingiz. Va yana qolasiz.', p:'O\'zingizni qanday ta\'riflar edingiz — metafora bilan?' },
      { e:'🎵', t:'Eng chiroyli qo\'shiqlar — og\'riq va baxtning uyg\'unligidan tug\'iladi. Sizning hayot qo\'shig\'ingiz ham shunday — va u go\'zal jaranglayapti.', p:'Hayotingiz qanday qo\'shiq bo\'lar edi?' },
      { e:'🕊️', t:'Kechirish — eng katta ozodlik. Qiyin kunlar sizga zarar yetkazgan bo\'lsa, ularni kechiring. Bu siz uchun — ular uchun emas.', p:'Nimani yoki kimni kechirish kerakligini his qilyapsizmi?' },
      { e:'🌙', t:'Qorong\'u tundan keyin tong otadi — bu qonuniyat. Siz bu qonuniyatni yashab bilasiz. Bugungi nur — o\'sha tongi unutmaysiz.', p:'Eng og\'ir davrdan keyin nima his qildingiz?' },
      { e:'🏅', t:'Har bir yiqilishdan turib chiqgan odamga medal berilishi kerak. Siz bunday medalga loyiqsiz — bir emas, ko\'p marta. O\'zingizni tabriklash vaqti.', p:'O\'zingizni qaysi jihatdan kuchli deb bilasiz?' },
    ],
    creative: [
      { e:'🎨', t:'Baxtli vaqtlarda ijod — eng go\'zal hosilini beradi. Qo\'lingga bo\'yoq yoki qalam ol, bugungi kayfiyatingni ranglar bilan ifodala. Hech qanday qoida yo\'q.', p:'Bugungi kayfiyating qaysi rangda bo\'lardi?' },
      { e:'🎵', t:'Quvonch — eng yaxshi ijodiy energiya. Bugun biror kuy chalgin, rasm chizgin, she\'r yozgin. Bu lahzani san\'atga aylantirib qo\'y — u abadiy qoladi.', p:'Agar bugungi kayfiyating qo\'shiq bo\'lsa, uning sarlavhasi nima?' },
      { e:'✏️', t:'Sening ijodiy potensialingga chek yo\'q — bugun uni ochib tashlash vaqti! Baxtli ko\'ngil — har bir yaratilishda iz qoldiradi. Ijod qil, shoshmasdan.', p:'Qaysi ijodiy narsani uzoqdan beri qilmoqchi edingiz?' },
      { e:'🌸', t:'Tabiat — eng katta artist. U hech qachon o\'zini cheklamaydi — gul qanday rang olmoqchi bo\'lsa, o\'sha rangda ochiladi. Siz ham bugun shunday oching.', p:'Agar tabiat ruhi bo\'lganingizda nima yaratardingiz?' },
      { e:'📸', t:'Bugungi lahzani rasm tushir — telefon yoki ko\'z bilan. Go\'zal narsalar hamma yerdadir, faqat ko\'rish kerak. Sen bugun ko\'rish imkoniyatiga egasan.', p:'Bugun qaysi go\'zal narsani suratga oldinmi?' },
      { e:'🎭', t:'Hayot — katta teatr, va siz bosh rolni o\'ynayapsiz. Bugun bu rolni to\'liq, qo\'rqmasdan, vijdonan o\'ynang. Tomosha qilayotganlar sizni kutmoqda.', p:'Hayot rolida o\'zingizni qanday o\'ynayapsiz?' },
      { e:'🎪', t:'Ijod — o\'yin. Va siz bugun o\'ynashga tayyor. Jiddiylikni bir chetga qo\'yib, faqat his qilib ko\'ring — nima chiqadi? Natija ajablantirishi mumkin.', p:'Oxirgi marta o\'yin qilganingizdek ijod qilganingiz qachon?' },
      { e:'🌊', t:'Ijod — dengiz kabi. U ba\'zan sokin, ba\'zan to\'lqinli. Bugun to\'lqin kuchli — unda suzib yuring, ichiga kirgin. Nima topasiz bilmaysiz.', p:'Ijodiy jarayon sizga qanday his beradi?' },
      { e:'💡', t:'G\'oyalar — hamma vaqt sizda. Lekin ko\'pchiligi eshik qoqib o\'tadi — siz eshitmasangiz ketadi. Bugun eshiklaringizni ochib qo\'ying.', p:'Oxirgi qanday g\'oya miyangizda o\'tib ketdi?' },
      { e:'🎀', t:'Ijod — o\'z-o\'zingizga yozgan sevgi xati. Qo\'lingizdan chiqadigan har narsa — sizning imzongiz, sizning izingiz. Bugun chiroyli iz qoldiring.', p:'Ijodingizdan qaysi biri siz uchun eng qimmatli?' },
      { e:'🌈', t:'Har xil rang aralashganda go\'zal rasm chiqadi — xuddi hayotdagi quvonch va qayg\'u aralashganda chiroyli hayot chiqadi. Siz bugun o\'sha go\'zal rasmsin.', p:'Hayotingizni qanday ranglarda tasvirlaysiz?' },
      { e:'🦋', t:'Ijod — o\'zgarishning belgi. Kapalak qo\'rqmasdan qanot yoyadi — siz ham shunday. Bugungi ijodiy cesaratni o\'zingizga ruxsat bering.', p:'Nima yaratishdan qo\'rqayotgan bo\'lsangiz — aynan o\'shani yozing.' },
    ],
    relation: [
      { e:'💕', t:'Baxtli ekanligingda atrofingizdagilarga mehr ulash! Birovga "sen menga muhimsan" demak — bu eng katta sovg\'a. Kim bugun shu so\'zni eshitishi kerak?', p:'Bugun kimga rahmat yoki mehr bildirasiz?' },
      { e:'🌷', t:'Sevgi — ulashilganda ko\'payadi. Sen bugun boshqalarga yorug\'lik ulasha olasan. Atrofingdagi odamlar sening baxtingni his qilsin.', p:'Seni sevadigan odamlar haqida bir narsa yozing.' },
      { e:'🤗', t:'Munosabatlar — baxtli paytlarda mustahkamlanadi. Bugun birov bilan chinakam suhbatlash, telefonni qo\'y va ko\'zlarga qara. Bu lahzani his qiling.', p:'Kimni eng ko\'p sog\'inayapsiz?' },
      { e:'🌸', t:'Hayotdagi eng go\'zal narsalar — odamlar. Sen bugun ularga ko\'proq e\'tibor qil. Bir tabassum, bir mehribon so\'z — bu katta farq yaratadi.', p:'Bugun kimga biror yaxshilik qilasiz?' },
      { e:'💌', t:'Uzoq vaqtdan beri xabar yozmaganing birov bormi? Bugun yurak bo\'lib yozing — oddiy, samimiy. Odamlar kutadi, faqat hammasi qo\'rqadi.', p:'Kimga xabar yozishni uzoq vaqt kechiktirgansiz?' },
      { e:'🫂', t:'Quchoqlash — eng qadimiy til. Bugun yaqinlaringizni quchoqlang — so\'zsiz, faqat his qilib. Ba\'zan so\'zlar ortiqcha bo\'ladi.', p:'Oxirgi marta kimni chinakam quchoqladingiz?' },
      { e:'🤝', t:'Munosabatlar — ikki tomonga ham energiya beradi. Siz bugun boshqalarga kuch bering — va ular ham sizga beradi. Bu aylanma doira.', p:'Qaysi munosabat sizga eng ko\'p kuch beradi?' },
      { e:'🌟', t:'Ba\'zan eng yaxshi narsani qilish — shunchaki yonida bo\'lish. So\'z kerak emas, maslahat kerak emas — faqat mavjudlik. Bu ham katta mehr.', p:'Kim sizning faqat yoningizda bo\'lishingizga muhtoj?' },
      { e:'💫', t:'Odamlar bir-biridan o\'rganadi — siz ham boshqalarning hayotiga dars bo\'lyapiz, bilmasangiz ham. Bugun qanday dars bo\'lmoqchisiz?', p:'Boshqalarga qanday o\'rnak bo\'lmoqchisiz?' },
      { e:'🎀', t:'Munosabatlarda eng qimmatli narsa — haqiqiy bo\'lish. Niqob taqib boshqalarga yoqishga urish emas, balki o\'zingiz bo\'lish. Bugun o\'zingiz bo\'ling.', p:'Qaysi munosabatda o\'zingiz bo\'layapsiz?' },
      { e:'🌈', t:'Turli xil odamlar — turli xil ranglar. Siz ularning barchasidan nimadir o\'rgana olasiz. Bugun yangi odam bilan gaplashgin — u sizni ajablantirishi mumkin.', p:'Oxirgi kimdan nimani o\'rgandingiz?' },
      { e:'🍀', t:'Sevgi — tanlov. Har kuni siz o\'z sevganlaringizni qaytadan tanlaysiz. Bugun bu tanlovni ongli ravishda qiling va ularga bildiring.', p:'Kimni bugun qaytadan tanlar edingiz?' },
    ],
  },

  sad: {
    self: [
      { e:'🫂', t:'Tushkun bo\'lish — insoniy, kuchsizlik emas. O\'zingga nisbatan mehribon bo\'l — xuddi eng yaqin do\'stingga muomala qilganday. Bu his o\'tadi, sen esa qolasan.', p:'"Hozir o\'zimga nima kerak?" — yozing.' },
      { e:'🌙', t:'Ba\'zan kayfiyat tushib ketadi — bu organizming dam olish so\'rashi. O\'zingga vaqt ber. Yig\'lasang yig\'la. Bu zaiflik emas — bu davoning bir qismi.', p:'Hozir o\'zing uchun eng yaxshi narsa nima ekan?' },
      { e:'🕊️', t:'Sen bu his qilayotgan og\'irlikning sababi bor. O\'zingni ayblamagin. Hamma tushkun bo\'ladi — va siz bu holat bilan kurashyapsiz — bu kuchlilik.', p:'"O\'zim haqida nima yaxshi narsa bilaman?" — 3 ta yoz.' },
      { e:'💙', t:'Kayfiyat tushganda dunyoqarash qorayadi — lekin bu haqiqat emas. Sen haqiqatdan ko\'ra qiyinroq vaqtda turgan odamsan. Buyon bo\'l — yorug\'lik bor.', p:'"Bu his qachon o\'tadi?" — o\'zingga yozing.' },
      { e:'🌿', t:'O\'simlik qurib qolmasin deb suv berish kerak. Siz ham hozir o\'zingizga "suv" bering — dam, mehr, tushunish. O\'zingizga g\'amxo\'r bo\'ling.', p:'O\'zingizga g\'amxo\'rlik uchun bugun nima qilasiz?' },
      { e:'🌸', t:'Gul hamma vaqt ochiq bo\'lmaydi — u ham ba\'zan yopiladi, dam oladi. Bu uning zaifligidan emas, tabiiyligidan. Sen ham shunday — dam olishing mumkin.', p:'Qachon oxirgi marta o\'zingizga to\'liq dam oldingiz?' },
      { e:'🫶', t:'O\'z-o\'zingni sevish — hamma vaqt oson emas. Ayniqsa tushkun paytlarda. Lekin aynan shu paytlarda bu eng muhim. O\'zingizga mehribon so\'zlar yozing.', p:'O\'zingizga bitta mehribon gap ayting.' },
      { e:'🌱', t:'Tushkun paytlar — o\'sishning ko\'rinmas davri. Ildizlar yerning tubida ishlayapti — siz ko\'rmaysiz, lekin o\'sish davom etmoqda. Sabr qiling.', p:'Hozir ichingizda nima o\'syapti deb o\'ylaysiz?' },
      { e:'🍃', t:'Barglar to\'kilib ketganda daraxt kurashini to\'xtatmaydi — u bahorgacha kuch yig\'adi. Sen ham hozir kuch yig\'ayapsan. Bu yetarli.', p:'Bu davrdan qanday kuch yig\'ayapsiz?' },
      { e:'💜', t:'O\'zingizni tushunish — eng katta ish. Hozir siz shu ish bilan band ekanmisiz — bu juda katta qadam. Ko\'pchilik bu qadam oldini olmaydi.', p:'Hozir o\'zingiz haqida nima o\'rganyapsiz?' },
      { e:'🌊', t:'To\'lqin balandiga ko\'tarilmaydi, pastga ham tushadi. Bu tabiat qonuni. Hozir pastga tushaversin — lekin bilgin: keyingisi yana ko\'tariladi.', p:'Bu paytlarda o\'zingizga nima deysiz?' },
      { e:'🕯️', t:'Bir sham qorong\'uni yoritadi. Hozir siz uchun o\'sha sham bo\'ladigan bitta narsa toping — kichkina bo\'lsa ham. Bir narsa yetarli.', p:'Bugun sizni biroz yoritadigan bitta narsa nima?' },
    ],
    goals: [
      { e:'🌱', t:'Tushkun paytlarda maqsadlar uzoq ko\'rinadi — bu ko\'zning hiylasi. Faqat bugun uchun bitta kichik narsa qil. Katta o\'zgarish kichik kunlardan tuziladi.', p:'1 ta juda kichik, hozir bajara oladigan narsa yozing.' },
      { e:'🌧️', t:'Ekinlar yomg\'irda ham o\'sadi. Sen ham hozir o\'syapsan — sezmagan bo\'lsang ham. Maqsadlaring seni kutmoqda, shoshma.', p:'Qaysi maqsad hozir eng muhim ko\'rinayapti?' },
      { e:'🔮', t:'Hozir hamma narsa qiyin — bu normal. Lekin kelajak sen tasavvur qilayotganday qorong\'i emas. Bitta qadam yetarli, faqat bitta.', p:'"Yaxshi bo\'lganda nima qilmoqchiman?" — yozing.' },
      { e:'🧭', t:'Yo\'l ko\'rinmasa ham — yo\'nalish bor. Kompas har doim shimolni ko\'rsatadi. Siz uchun o\'sha kompas nima — maqsad, qadriyat, tush?', p:'Hayotingizda sizga yo\'nalish beradigan narsa nima?' },
      { e:'🌙', t:'Tunni o\'tkazmasdan tong otmaydi. Hozir siz tunning o\'rtasida bo\'lishingiz mumkin — lekin tong keladi. Maqsadlaringiz tong bilan birga ochiladi.', p:'Tongga qadar nima qilasiz?' },
      { e:'🐢', t:'Toshbaqa ham o\'z vaqtida yetib boradi. Tez yurish shart emas — to\'xtamaslik muhim. Hozir sekin bo\'lsa ham — davom eting.', p:'Bu davrda ham qilayotgan bitta ish nima?' },
      { e:'💫', t:'Yiqilish — mag\'lubiyat emas. Yiqilib, ko\'zingizni ochib, qaytadan turish — bu g\'alaba. Siz hozir o\'sha jarayondasiz.', p:'O\'zingizni qanday tavsiflar edingiz — kuchli yoki zaif?' },
      { e:'🌺', t:'Gul qishda ham ildiz qo\'yadi — bahorda chiqish uchun. Siz hozir ildiz qo\'yayapsiz. Bu ko\'rinmas, lekin eng muhim ish.', p:'Hozir siz uchun ildiz nima — nima sizni tutib turadi?' },
      { e:'🔑', t:'Har bir qiyin davr — yangi quvvatning kaliti. Hozir siz o\'sha kalitni topish yo\'lidasiz. Qidirishni to\'xtatmang.', p:'Bu davrdan qanday yangi kuch chiqarasiz?' },
      { e:'🌊', t:'Dengizchi to\'lqinni boshqara olmaydi — lekin yelkanni to\'g\'rilay oladi. Siz ham hozir shartlarni boshqara olmayapsiz — lekin o\'z reaktsiyangizni boshqarasiz.', p:'Bu vaziyatda nimani boshqarishingiz mumkin?' },
      { e:'⭐', t:'Yulduzlar faqat qorong\'uda ko\'rinadi. Hozir siz yulduzlaringizni ko\'ryapsiz — ularni yodingizda saqlang, ular hamma vaqt shu yerda bo\'ladi.', p:'Tushkun paytlarda qaysi "yulduzlar" ko\'rinadi?' },
      { e:'🌿', t:'Tabiat hech qachon shoshilmaydi — lekin hamma narsani o\'z vaqtida qiladi. Siz ham o\'z vaqtingizda bo\'lishingiz mumkin. O\'z ritmingizda yuring.', p:'O\'z ritmingizda yurish deb nimani tushunasiz?' },
    ],
    hard: [
      { e:'🌊', t:'Qiyin to\'lqinlar o\'tadi — dengiz har doim tinchiydi. Hozir to\'lqin ichida bo\'lsang ham, qirg\'oq bor. Nafas ol, suzib boraver.', p:'Hozir seni eng ko\'p qiynayotgan narsa nima?' },
      { e:'☁️', t:'Bulutli kunlar abadiy emas. Sen allaqachon ko\'p og\'ir kunlarni o\'tkazgansiz — bu ham o\'tadi. Bugungi og\'irlik ertaga sizni kuchaytiradi.', p:'O\'tkazgan qiyin kunlardan qaysi biridan kuch olasiz?' },
      { e:'🫶', t:'Yig\'lash — kuchlilik. Hissiyotlarni his qilish — sog\'lom. O\'zingga ruxsat ber — his qilishga, og\'rishga. Lekin bilgin: bu ham o\'tadi.', p:'"Bu qiyinchilikdan nima o\'rganaman?" — yozing.' },
      { e:'🌱', t:'Eng qiyin paytlarda ham o\'sish bordir. Shunchaki ko\'rinmaydi. Ildizlar chuqurroq ketayapti — daraxt balandroq bo\'lish uchun.', p:'Bu qiyin davrda qanday o\'sishingiz mumkin?' },
      { e:'💪', t:'Siz qiyinchiliklarni yengib o\'tgan odamsiz — bir marta emas, ko\'p marta. Bu haqiqat. O\'sha kuchni hozir ham topasiz — u sizda bor.', p:'Qanday qiyin vaziyatni yengib o\'tgansiz?' },
      { e:'🌙', t:'Qorong\'u tunlarda odamlar ichini ko\'radi — o\'z kuchini, o\'z qo\'rquvini, o\'z orzularini. Siz hozir shuni ko\'ryapsiz. Bu narsa ko\'pchilikka nasib etmaydi.', p:'Hozirgi qiyinchilik sizga nima ko\'rsatyapti?' },
      { e:'🕯️', t:'Bitta sham qorong\'uni yoritadi. Hozir siz uchun o\'sha sham — o\'zingiz. O\'z yorug\'ligingizni o\'chirmaslik — bu hozirgi eng katta ish.', p:'O\'z ichingizda qanday yorug\'lik bor?' },
      { e:'🦅', t:'Burgut qancha baland uchsa, shamol shuncha kuchli urishini biladi. Lekin u shamolni dushman deb bilmaydi — balkim ko\'taradigan kuch deb biladi.', p:'Bu qiyinchilikni ko\'taruvchi kuchga aylantirsangiz?' },
      { e:'🌸', t:'Gul bahorda chiqadi — lekin uning ildizi qishda mustahkamlanadi. Siz hozir qish davridasiz. Bu muhim davr — keyingi gulning asosi shu.', p:'Hozirgi davr kelajagingiz uchun nima yaratyapti?' },
      { e:'🔥', t:'Oltin olovda sinovdan o\'tadi. Siz ham shu jarayondasiz. Bu og\'riq — lekin natija oltin. O\'sha oltinni ko\'r.', p:'Bu sinov sizni qanday oltinga aylantirmoqda?' },
      { e:'🌿', t:'Tabiiy davolar sekin ta\'sir qiladi — lekin chuqur. Siz hozir o\'zingizni davolashning tabiiy jarayonindasiz. Shoshilmang — bu to\'g\'ri yo\'l.', p:'O\'zingizni davolash uchun nima qilyapsiz?' },
      { e:'🏔️', t:'Tog\'ga chiqish qiyin — lekin yuqoridan ko\'rinish ajoyib. Hozir qiyin qism — lekin cho\'qqi ko\'rinatyapti. To\'xtamang.', p:'Bu yo\'lning oxirida nima bor deb o\'ylaysiz?' },
    ],
    creative: [
      { e:'🎭', t:'Eng chuqur ijod — og\'riqdan tug\'iladi. Hissiyotlaringizni chiqarib tashlang: she\'r, rasm, yoki faqat qog\'ozga so\'zlar. Baholash kerak emas — to\'kib soling.', p:'Hozirgi his-tuyg\'ularingizni bir ranggda ifodalasangiz qanday rang?' },
      { e:'🖤', t:'Qora ranglarning o\'z go\'zalligi bor. Hozir his qilayotgan narsangni san\'atga aylantir. Bu — eng kuchli terapiya, eng samimiy ijod.', p:'Rasm chizing — nima bo\'lsa ham. Keyin unga nom bering.' },
      { e:'📝', t:'Og\'riq — eng yaxshi yozuvchi. Hozirgi his-tuyg\'ularingizni yozing — tartibsiz, to\'g\'ri. Keyin o\'qib ko\'ring — qanchalik jasur ekansiz.', p:'Hozirgi his-tuyg\'ularingizni to\'g\'ridan-to\'g\'ri yozing.' },
      { e:'🎵', t:'Eng og\'riqli qo\'shiqlar — eng ko\'p tinglanadiganlari. Chunki haqiqiy. Siz ham haqiqiy his qilyapsiz — bu sizi yolg\'iz qilmaydi, balki bog\'laydi.', p:'Hozirgi holatni eng yaxshi ifodalovchi qo\'shiq nima?' },
      { e:'🌧️', t:'Yomg\'ir — tabiatning yig\'ishi. Lekin u o\'simliklarni oziqlantiradi. Sizning yig\'ingiz ham — ichingizni tozalaydi va yangilaydi.', p:'Yig\'lash sizga qanday ta\'sir qiladi?' },
      { e:'🕯️', t:'Qorong\'uda yoqilgan sham — kimdir uchun yorug\'lik. Hozir siz his qilayotgan og\'riq — kimgadir ulanish, tushunish bo\'lishi mumkin.', p:'Sizning tajribangiz kimga yordam berishi mumkin?' },
      { e:'🌊', t:'Dengiz bo\'roni — eng kuchli to\'lqinlarni yaratadi. Sizning hissiyotlaringiz ham shunday — kuchli, chuqur, haqiqiy. Ularni san\'atga aylantiring.', p:'Hissiyotlaringizni qanday san\'atga aylantirmoqchisiz?' },
      { e:'🔮', t:'Ba\'zan biz o\'zimizni ijod orqali topamiz. Hozir yo\'q bo\'lib tuyulayotganingizda — yarating. Yaratilgan narsa — sizning izingiz.', p:'Hozir nima yaratmoqchisiz?' },
      { e:'💜', t:'Tasodifiy chiziqlar ham san\'at bo\'lishi mumkin. Tartibsiz so\'zlar ham she\'r. Hozir "yaxshi" bo\'lishini kutmang — shunchaki chiqaring.', p:'Bugun 5 daqiqa tartibsiz chizing yoki yozing.' },
      { e:'🌙', t:'Yozuvchilar ko\'pincha tunlari yozadi. Qorong\'u hissiyotlar — yorqin so\'zlarni tug\'diradi. Siz hozir o\'sha lahzadasiz.', p:'Bu lahzada qanday so\'zlar chiqadi?' },
      { e:'🎨', t:'Rangsiz bo\'yoq yo\'q — har bir rang o\'z joyida. Qorang\'u ranglar ham go\'zal rasm uchun kerak. Siz hozir o\'sha muhim rang bo\'layapsiz.', p:'Hayotingizning ranglari haqida yozing.' },
      { e:'📖', t:'Hayot kitobida ba\'zi sahifalar og\'irroq yoziladi. Lekin o\'sha sahifalar — kitobni haqiqiy qiladi. Bugungi sahifangizni yozing.', p:'Bugungi hayot kitobingizning sahifasini yozing.' },
    ],
    relation: [
      { e:'🤝', t:'Yolg\'iz his qilsangiz — bu his haqiqiy, lekin haqiqat emas. Birov sizni o\'ylayapti. Bugun bitta odamga qo\'ng\'iroq qiling — hatto qisqa bo\'lsa ham.', p:'Kim bilan suhbatlashsangiz yaxshi his qilasiz?' },
      { e:'💌', t:'Munosabatlar ba\'zan og\'ir bo\'ladi. Lekin samimiy bir so\'z ko\'p narsani o\'zgartiradi. Ichingizda saqlagan narsani — yozib qo\'ying avval.', p:'Kimga aytmoqchi bo\'lgan narsangiz bor? Yozing.' },
      { e:'🫂', t:'Hamma ham ba\'zan yolg\'iz his qiladi — bu insoniy. Lekin o\'zingizni yopib qo\'ymang. Birov sizni kutmoqda, siz bilmasangiz ham.', p:'"Kim meni haqiqatan tushunadi?" — deb yozing.' },
      { e:'🌸', t:'Ba\'zan so\'z kerak emas — faqat yonida bo\'lish kerak. Bugun kimningdir yonida bo\'ling yoki birovni yoningizda bo\'lishiga ruxsat bering.', p:'Kim hozir sizning yoningizda bo\'lishini istaysiz?' },
      { e:'💙', t:'Munosabatlarda og\'riq — ba\'zan siz muhim ekanligingizning belgisi. Agar muhim bo\'lmasa — og\'rimaydi. Shu og\'riq sizga nima aytmoqda?', p:'Bu munosabatdan nima istaysiz?' },
      { e:'🌷', t:'Kechirim — o\'zingiz uchun. Kimdir sizni og\'ritgan bo\'lsa, uni kechirish — ularni oqlamoq emas, o\'zingizni ozod qilmoq.', p:'Kimni kechirish kerakligini his qilyapsizmi?' },
      { e:'🌙', t:'Yolg\'iz tunlar — ba\'zan eng chuqur fikrlar keladi. Bu yolg\'izlik vaqtini qadrligini his qiling — u ham o\'tib ketadi.', p:'Yolg\'izlikda o\'zingizdan nima o\'rgandingiz?' },
      { e:'🤲', t:'Yordam so\'rash — kuchlilik. Hech kim hamma narsani yolg\'iz ko\'tara olmaydi. Bugun kimgadir murojaat qilish — bu eng jasur qadam.', p:'Kimdan yordam so\'rashingiz mumkin?' },
      { e:'💫', t:'Ba\'zan munosabatlar vaqtinchalik soviydi — bu abadiy emas. Isitish uchun birinchi qadam — siz qo\'ying. Birinchi bo\'ling.', p:'Sovigan munosabatni isitish uchun nima qilasiz?' },
      { e:'🕊️', t:'Munosabatlardagi og\'riq — ikki inson orasidagi bo\'shliqdan keladi. O\'sha bo\'shliqni to\'ldirish uchun birinchi so\'zni siz ayting.', p:'Qaysi so\'z munosabatingizni yaxshilashi mumkin?' },
      { e:'🌿', t:'Munosabatlar o\'simlik kabi — parvarish kerak. Ba\'zan qurib qoladi — lekin ildiz tirik bo\'lsa, suv bersa qayta o\'sadi.', p:'Qaysi munosabatga "suv" kerak?' },
      { e:'🌈', t:'Har xil odamlar turli ranglar — ular bilan munosabat hayotingizni boyitadi. Hatto og\'riq bergan odam ham sizga biror narsa o\'rgatdi.', p:'Og\'ritgan odam sizga nima o\'rgatdi?' },
    ],
  },

  strong: {
    self: [
      { e:'🦁', t:'Bu kuchni his qilyapsan — demak u hamma vaqt ichingda bor edi! Siz o\'z hayotingizning qahramonisiz. Bugun shu kuchni biron muhim ishga yo\'naltiring.', p:'Bugun o\'zingdan faxrlanishingizga sabab bo\'lgan narsa yozing.' },
      { e:'⚡', t:'Kuchli ekanligingizda o\'zingizni sinab ko\'ring! Hozir siz uchun imkonsiz narsa yo\'q. Uzoq vaqt qo\'rqib turgan ishingizni bugun boshlang.', p:'"Agar muvaffaqiyat kafolatlangan bo\'lganda nima qilardim?" — yozing.' },
      { e:'🔥', t:'Bu energiya — sovg\'a. Uni isrof qilmang. Hozir siz uchun biror katta qaror qabul qilish vaqti — siz tayyor, vaqt ham tayyor.', p:'Qaysi qarorni uzoq vaqtdan beri kechiktirayapsiz?' },
      { e:'💎', t:'Siz allaqachon ko\'p narsani yengdingiz — bu kuch isbotlangan. Bugun o\'sha kuchni tan oling. Siz oddiy odam emas — siz kurashgan va g\'alaba qilgan odamsiz.', p:'O\'tgan qiyinchiliklardan qanday kuch oldingiz?' },
      { e:'🏆', t:'G\'alaba — bu hamma vaqt tashqarida emas, ba\'zan ichingizda. Bugun o\'z-o\'zingizni yengdingiz — qo\'rquvni, shubhani, kechiktirishni. Bu eng katta g\'alaba.', p:'Bugun qaysi ichki to\'siqni yengdingiz?' },
      { e:'🌟', t:'Siz bugun eng yaxshi versiyangizdasiz — va ertaga bundan ham yaxshiroq bo\'lasiz. Bu o\'sish to\'xtamaydi, chunki siz unga ruxsat berayapsiz.', p:'"Eng yaxshi versiyam qanday ko\'rinadi?" — yozing.' },
      { e:'🦅', t:'Burgut faqat bo\'ron paytida baland uchadi — yel uni ko\'taradi. Siz ham qiyinchilikni kuch manbaiga aylantirgan odamsiz. Bu — noyob qobiliyat.', p:'Qanday qiyinlik sizi kuchaytirdi?' },
      { e:'🌊', t:'Dengiz qanchalik chuqur bo\'lsa, shunchalik ko\'p sirlar saqlaydi. Siz ham chuqursiz — va bu chuqurlikda kuchingiz manbai yashiringan.', p:'O\'z kuchingizning manbasini qanday ko\'rasiz?' },
      { e:'🔮', t:'Siz hozir o\'z imkoniyatingizni his qilyapsiz — bu imkoniyat cheksiz. Qaysi sohada bu kuchni ishlatmoqchisiz?', p:'Kuchingizni qaysi sohada eng ko\'p ishlatmoqchisiz?' },
      { e:'🌺', t:'Kuchli odamlar ham o\'zlariga nisbatan mehribon bo\'lishi kerak. Kuch — faqat tashqariga emas, o\'zingizga ham qaratilsin.', p:'O\'zingizga qanday mehribon bo\'la olasiz?' },
      { e:'🎯', t:'Siz nima xohlashingizni bilasiz — va uni olish uchun kuchingiz bor. Bu kombinatsiya — nadir. Uni bugun ishga soling.', p:'Hozir eng ko\'p xohlagan narsangiz nima?' },
      { e:'🚀', t:'Raketa uchish uchun ko\'p yonilg\'i sarflaydi — lekin bir marta uchsa, kosmosga yetadi. Siz hozir uchish paytingizdasi. Yonadigan vaqt keldi.', p:'Hozir "uchish" uchun nima kerak?' },
    ],
    goals: [
      { e:'🏔️', t:'Kuchli paytlarda tog\'lar qo\'zg\'aladi! Eng katta orzuingizni esga oling — bugun unga bir muhim qadam qo\'ying. Ertaga emas, bugun.', p:'Eng katta orzuyingizni 3 qadamga bo\'ling.' },
      { e:'🎯', t:'Siz hozir maqsadga eng yaqin joydasiz. Bu energiyani yo\'qotmang — harakat qiling! Qaysi bitta ish bugun eng katta farq yaratadi?', p:'Bugun bajarilsa, hayotingiz o\'zgaradigan bir ish yozing.' },
      { e:'🚀', t:'Kuch + maqsad = hayot o\'zgaradi. Siz ikkalasiga egasiz hozir. Bu kombinatsiya nadir — qo\'ldan bermang.', p:'"Bu oy nima erishmoqchiman?" — aniq yozing.' },
      { e:'⚡', t:'Hozir sizda kuch bor — uni maqsadga yo\'naltiring. Katta narsalar ham bitta jiddiy harakatdan boshlanadi. Bugun o\'sha harakatni qiling.', p:'Maqsadingizga bugun qanday "jiddiy qadam" tashlaysiz?' },
      { e:'💡', t:'Kuchli paytlarda eng yaxshi g\'oyalar keladi — ularni yozib qo\'ying. Keyinchalik bu g\'oyalar oltin bo\'lishi mumkin.', p:'Hozirgi eng kuchli g\'oyangiz nima?' },
      { e:'🌟', t:'Siz qila olasiz — bu faqat gap emas, haqiqat. Bugun o\'sha "qila olmaydi" degan ovozni jim qiling va birinchi qadamni qo\'ying.', p:'Qaysi maqsadda o\'zingizga "qila olaman" deyishingiz kerak?' },
      { e:'🎪', t:'Hayot — imkoniyatlar yarmarkasi. Hozir siz kuchli ekanmisiz — demak o\'sha yarmarkada nima xohlashingizni bilasiz. Borib oling.', p:'Hayot yarmarkasida siz uchun nima bor?' },
      { e:'🌊', t:'To\'lqin yuqori bo\'lganda — surfing eng yaxshi. Siz hozir o\'sha to\'lqin ustidasi. Bu lahzani maxsus maqsad uchun ishlating.', p:'Bu to\'lqinni qaysi maqsad uchun ishlatamiz?' },
      { e:'🦋', t:'Kapalak bir yo\'nalishda uchadi — kuch sarflamaydi, lekin manzilga yetadi. Siz ham hozir o\'sha yo\'nalishni aniq biling va uchib keting.', p:'Maqsadingizga boradigan eng to\'g\'ri yo\'l nima?' },
      { e:'🔑', t:'Siz o\'zingizning qulfi oldida turgan odamsiz — va kalitingiz qo\'lingizda. Bugun shu eshikni oching.', p:'Qaysi "qulf" ni ochish vaqti keldi?' },
      { e:'🌈', t:'Kuchli paytlarda katta narsalarni orzu qilish — qo\'rqinchli emas. Hozir orzu qiling — va o\'sha orzuni haqiqatga aylantirish uchun birinchi ish nima?', p:'Eng katta orzuyingizni yozing.' },
      { e:'🏅', t:'Maqsadga erishish — medal olish. Lekin medaldan oldin ko\'p treninglar bor. Bugun treningni boshlamaysizmi?', p:'Maqsadingiz uchun bugungi "trening" nima?' },
    ],
    hard: [
      { e:'🛡️', t:'Qiyinchiliklar seni shunday kuchaytirdi. Har bir muammo — trenirovka edi. Hozir sen ishlatib o\'rganilgan kuch — haqiqiy kuch.', p:'Eng qiyin sinovingiz — sizni qanday o\'zgartirdi?' },
      { e:'💎', t:'Olmoslar bosim ostida yaratiladi. Sen — olmossan. Hozirgi qiyinchiligingga bosh ko\'tarib qara — sen uni yengasiz, chunki sen yenggan odamsan.', p:'"Qiyinchilik meni kuchaytiradi, chunki..." — yozing.' },
      { e:'🌊', t:'To\'lqin qanchalik katta bo\'lsa, suzuvchi shuncha kuchayadi. Siz qiyinchiliklar to\'lqinida suzib o\'rgangan odamsiz. Bu — tengsiz tajriba.', p:'Hozirgi muammoning ichida qanday imkoniyat yashiringan?' },
      { e:'🦁', t:'Sher qanchalik ko\'p ovlansa, shuncha yaxshi ov qilishni o\'rganadi. Siz ham har bir qiyinlikda yaxshiroq bo\'lyapsiz. Bu — o\'sish.', p:'Oxirgi qiyinlikdan nima o\'rgandingiz?' },
      { e:'⚔️', t:'Jangchi faqat janglarda shаkllаnadi. Siz hozir o\'sha jangni olib boryapsiz — va siz g\'alaba qilasiz, chunki taslim bo\'lmadingiz.', p:'Hozirgi "jangingiz" qaysi?' },
      { e:'🔥', t:'Olov faqat yonadigan narsalarni yoqadi. Siz hozir olov ichida ekanmisiz — u sizni yoqa olmaydi, chunki siz metall kabi mustahkamsiz.', p:'O\'zingizni bu olovdan qanday himoya qilayapsiz?' },
      { e:'🌺', t:'Qizil gul — eng kuchli va o\'tkir tikanlari bor. Lekin bu uni kam go\'zal qilmaydi — aksincha. Siz ham shu gul kabi — kuchli va go\'zal.', p:'Kuch va go\'zallik birgalikda bo\'lishi mumkinmi? Fikringizni yozing.' },
      { e:'🏔️', t:'Tog\'ning cho\'qqisini faqat chiqib ko\'rganlar biladi. Siz o\'sha yo\'lda ekanmisiz — va cho\'qqiga yetgan odam manzara haqida gapiradi, og\'riq haqida emas.', p:'Bu qiyinlikning oxirida qanday manzara bo\'ladi?' },
      { e:'🌙', t:'Tun eng qorong\'usi — tongga yaqinlashganda bo\'ladi. Siz hozir shu joyda bo\'lishingiz mumkin. Tong yaqin.', p:'Bu qorong\'ulikda nima ko\'ryapsiz?' },
      { e:'💪', t:'Qiyinchiliklar sizni sinaydi — lekin sindira olmaydi. Chunki siz allaqachon ko\'p narsani yengdingiz. Bu ham siz uchun yana bir g\'alaba bo\'ladi.', p:'O\'zingizga bu to\'siqni yengganingizdan keyin nima deysiz?' },
      { e:'🦅', t:'Burgut shamol bilan uchadi — unga qarshi emas. Qiyinchiliklarni ham shu tarzda ishlatish mumkin. Ular sizni orqaga tortmaydi — balki yuqoriga ko\'taradi.', p:'Bu qiyinlikni kuch manbaiga qanday aylantirish mumkin?' },
      { e:'🌿', t:'O\'t-o\'lan temir beton orqali ham o\'sadi. Siz ham shunday — hech qanday to\'siq sizni to\'xtata olmaydi. O\'sish — sizning tabiatingiz.', p:'Hozir qaysi "beton" orqali o\'sib chiqayapsiz?' },
    ],
    creative: [
      { e:'🎨', t:'Kuchli paytlarda ijod — portlaydi! Hozir biror narsani yarating: rasm, she\'r, musiqa. Bu kuch to\'lqini ijodingizga eng chiroyli ranglarni beradi.', p:'Qaysi ijodiy loyihani shu kuch bilan yakunlaysiz?' },
      { e:'🖌️', t:'Ijod qilmoq — kuch ishlatmoq. Siz bugun kuchlisiz — demak bugun yaratasiz. O\'zingizni cheklamang, barcha g\'oyangizni chiqarib tashlang.', p:'Agar vaqt va resurs chegarasi bo\'lmasa, nima yaratasiz?' },
      { e:'✨', t:'Kuchli odamlar eng jasur ijodiy qarorlar qiladi. Bugun biror narsani yarating va uni boshqalarga ko\'rsating — bahosi yo\'q!', p:'Kimga ko\'rsatishdan qo\'rqqan ijodiy ishingiz bormi?' },
      { e:'🔥', t:'Bu energiya bilan ijod qiling — hozir kayfiyatingiz to\'liq va kuchli. Bugun yaratgan narsa — sizning holatingizdagi eng kuchli ifodalanishingiz.', p:'Hozir o\'z kuchingizni qanday ifodalamoqchisiz?' },
      { e:'⚡', t:'Ijodiy chaqmoq — aynan shu paytda uradi. Uni tutib oling — daftarga, kanvasga, yoki faqat miyangizga yozing. U qaytib kelmaydi.', p:'Hozir qanday ijodiy g\'oya chaqmoqlab o\'tyapti?' },
      { e:'🌊', t:'Kuchli to\'lqin — eng yaxshi dalqin moshinasi. Siz hozir shu to\'lqin ustidasi. Surfing qiling — ijodiy, erkin, qo\'rqmasdan.', p:'Bu to\'lqinda qanday "surfing" qilasiz?' },
      { e:'🎭', t:'Kuchli odamlar eng katta rollarni o\'ynaydi — hayotda ham, san\'atda ham. Bugun qaysi rolni to\'liq o\'ynamoqchisiz?', p:'Bugungi "rol" ingiz nima?' },
      { e:'💡', t:'Eng yaxshi ijodlar — kuch va his uyg\'unligidan chiqadi. Siz ikkalasiga egasiz hozir. Ularni birlashtirsangiz nima yaratiladi?', p:'Kuch + hissiyot = qanday ijod?' },
      { e:'🌺', t:'Gul qanchalik kuchli bo\'lsa, shuncha chiroyli ochiladi. Siz ham bugun to\'liq ochilib, eng go\'zal versiyangizdasi. Buni ijodga aylantiring.', p:'Bugungi "ochilish" ni qanday ifodalaysiz?' },
      { e:'🏆', t:'G\'olib ijodkorlar — o\'z qo\'rquvlarini yenggan odamlar. Siz hozir kuchlisiz — demak o\'sha qo\'rquv ortida nima bor, u tomonga qadam qo\'ying.', p:'Ijodda qaysi qo\'rquvni yengmoqchisiz?' },
      { e:'🎯', t:'Ijod — nishon urish. Siz hozir kuchli va aniq ekanmisiz — o\'sha nishonni toping va uring. Muvaffaqiyat sizniki.', p:'Ijodda qaysi "nishon" ga urishni xohlaysiz?' },
      { e:'🌈', t:'Kuchli bo\'lganingizda eng ko\'p ranglar ko\'rinadi. Bugun o\'sha ranglarni qalamingizga to\'ling va qog\'ozga to\'king.', p:'Bugungi kuchingizni qaysi ranglarda ko\'rasiz?' },
    ],
    relation: [
      { e:'🌟', t:'Kuchli odamlar atrofidagilarni ko\'taradi. Bugun kimnidir ko\'taring — biror so\'z, biror yordam. Kuch — ulashilganda ko\'payadi.', p:'Kim hozir sizning qo\'llab-quvvatlashingizga muhtoj?' },
      { e:'🤲', t:'Siz bugun birovning hayotini o\'zgartira olasiz — hatto bilmasangiz ham. Biror yaxshilik qiling — kichkina bo\'lsa ham.', p:'Bugun kimga kutilmagan yaxshilik qilasiz?' },
      { e:'💪', t:'Munosabatlarda ham kuch ko\'rsatish vaqti. Uzoq vaqtdan beri aytolmagan narsangiz bormi? Bugun aytish vaqti keldi.', p:'Kimga aytmoqchi bo\'lgan muhim narsangiz bor?' },
      { e:'🌺', t:'Kuchli odamlar eng yaxshi do\'stlar ham bo\'ladi — chunki ular qo\'rqmasdan haqiqatni aytadi. Bugun birovga haqiqiy, mehribon fikr ayting.', p:'Kimga haqiqiy fikringizni aytishingiz kerak?' },
      { e:'🦋', t:'Siz bugun boshqalarga o\'zgarish uchun ilhom bo\'la olasiz. Bu katta mas\'uliyat — ammo siz unga tayyorsiz. Biror o\'rnak ko\'rsating.', p:'Kimga ilhom bo\'lmoqchisiz?' },
      { e:'🌊', t:'Kuchli odamlar ham ba\'zan yordam so\'raydi — bu zaiflik emas, donolik. Hozir kimdan yordam so\'rashingiz mumkin?', p:'Yordam so\'rash sizga qanday his beradi?' },
      { e:'🌸', t:'Munosabatlarda kuch — o\'zingiz bo\'lishdan keladi. Niqob taqib kuchli ko\'rinishdan emas, balki haqiqiy bo\'lib kuchli bo\'lishdan.', p:'Qaysi munosabatda o\'zingiz bo\'lasiz?' },
      { e:'💫', t:'Siz o\'zingiz bilmasdan ham boshqalarga kuch berayapsiz — odamlar sizni ko\'rib ilhomlanadi. Bu ulkan ta\'sir. Uni eslab qo\'ying.', p:'Kimga kuch va ilhom berayapsiz?' },
      { e:'🤗', t:'Kuchli quchoq — eng kuchli so\'z. Bugun yaqinlaringizni quchoqlang — so\'zsiz, faqat his qilib.', p:'Kim sizning quchog\'ingizga muhtoj?' },
      { e:'🎀', t:'Munosabatlarda eng katta sovg\'a — to\'liq diqqat. Bugun birovga to\'liq e\'tiboringizni bering — telefonsiz, fikrsiz, faqat u bilan.', p:'Kimga to\'liq diqqatingizni berasiz?' },
      { e:'🌷', t:'Kuchli odamlar ham yumshoq bo\'lishi mumkin — bu qarama-qarshilik emas. Bugun kimgadir yumshoq, mehribon bo\'ling.', p:'Kim sizning yumshoqligingizga muhtoj?' },
      { e:'🌿', t:'Munosabatlar o\'simlik kabi o\'sadi — doim parvarishga muhtoj. Siz hozir kuchli — o\'sha parvarishni qiling.', p:'Qaysi munosabatni parvarish qilish vaqti?' },
    ],
  },

  anxious: {
    self: [
      { e:'🌿', t:'Nafas oling. Hozir, shu daqiqada — siz xavfsiz. Xavotir ko\'pincha kelajak haqidagi fikr — haqiqat emas. Hozirga qayting: siz bu yerdasiz, va bu yetarli.', p:'Atrofingizdagi 5 ta narsani yozing — ko\'rib turganlaringizni.' },
      { e:'🍃', t:'Xavotir — siz muhim narsalarga qayg\'uyotganingiz belgisi. Lekin nafas oling — hamma narsa bir vaqtda hal bo\'lishi shart emas.', p:'3 marta chuqur nafas oling, so\'ng: "Hozir nima his qilyapman?" yozing.' },
      { e:'🫶', t:'O\'zingizga nisbatan yumshoq bo\'ling — siz hammasi yaxshi bo\'lishini xohlayapsiz, bu sevgi belgisi. Lekin siz ham xatolik qilishingiz mumkin — va bu normal.', p:'"O\'zimdan nimani talab qilyapman? Bu real ekanmi?" — yozing.' },
      { e:'🌸', t:'Xavotirli paytlarda o\'z-o\'zingizni sevish eng qiyin — va eng muhim. Hozir o\'zingizga bir mehribon so\'z ayting. Faqat bitta.', p:'O\'zingizga bitta mehribon gap ayting.' },
      { e:'🌙', t:'Tun qorong\'uda yulduzlar ko\'rinadi. Xavotirli paytlarda ham ichingizda yorug\'lik bor — u o\'chib ketmagan. Uni toping.', p:'Hozir ichingizda qanday yorug\'lik bor?' },
      { e:'🕯️', t:'O\'zingizga g\'amxo\'rlik — bu xudbin emas. Siz birovga yaxshi bo\'lish uchun avval o\'zingiz yaxshi bo\'lishingiz kerak. Hozir o\'zingizga vaqt bering.', p:'O\'zingizga g\'amxo\'rlik uchun bugun nima qilasiz?' },
      { e:'🌊', t:'To\'lqin kabi keladi xavotir — va kabi ketadi. Siz qirg\'oqsiz. U kelib, tegib, o\'tib ketadi. To\'xtab turing, nafas oling.', p:'Xavotir qachon va qanday o\'tib ketadi?' },
      { e:'🌿', t:'Tabiatda hech narsa shoshilmaydi — hamma narsa o\'z vaqtida bo\'ladi. Siz ham shoshilmaslik uchun haqingiz bor. O\'z vaqtingizni o\'zingiz belgilang.', p:'O\'z tempingizda yurish uchun nima kerak?' },
      { e:'💜', t:'Xavotir ichingizda qayd etilgan signaldir — nima muhimligini ko\'rsatadi. U dushman emas, xabarchi. Xabarni o\'qing, so\'ng xabarchi ketsin.', p:'Xavotir sizga nima xabar bermoqda?' },
      { e:'🫂', t:'Hamma ham ba\'zan xavotirlanadi — siz yolg\'iz emassiz. Bu sizni kuchsiz qilmaydi. Bu sizni insoniy qiladi — va bu ajoyib.', p:'Xavotirlaganingizda o\'zingizga nima deysiz?' },
      { e:'🌱', t:'Xavotir energiyasi — agar to\'g\'ri yo\'naltirilsa, kuchga aylanadi. Shu energiyani biror foydali ishga sarflang hozir.', p:'Bu energiyani qaysi foydali ishga sarflaysiz?' },
      { e:'🔮', t:'Ko\'p xavotirlagan narsalar hech qachon yuz bermaydi — statistika shuni ko\'rsatadi. Lekin shubha qilmang — hozirgi lahzaga qayting.', p:'Xavotirlagan narsalaringizning qanchasi haqiqiy bo\'ldi?' },
    ],
    goals: [
      { e:'🐾', t:'Maqsadlar ba\'zan katta ko\'rinadi — bu ko\'zning hiylasi. Ularni kichraytiring. Bugun faqat bitta, eng kichik qadamni qo\'ying. Shuncha yetarli.', p:'Eng katta maqsadingizni 10 ta kichik qadamga bo\'ling.' },
      { e:'🌱', t:'Tezlash kerak emas. O\'simliklar ham shoshmasdan o\'sadi. Siz ham o\'z vaqtingizda yetib borasiz — bu musobaqa emas.', p:'"O\'zimga qancha vaqt beraman?" — yozing.' },
      { e:'🧭', t:'Xavotirli paytlarda faqat keyingi qadamni ko\'r — butun yo\'lni emas. Kompas to\'liq xaritani bilmaydi, lekin yo\'nalishni ko\'rsatadi.', p:'Bugungi bitta, kichik qadamingiz nima?' },
      { e:'🌸', t:'Xavotir maqsadingizga borish yo\'lingizni to\'smaydi — lekin siz ruxsat bersangiz, to\'sadi. Bugun xavotirga "men seni eshitdim, lekin boryapman" deng.', p:'Maqsadingizga xavotiringiz bilan birga qanday borish mumkin?' },
      { e:'🔑', t:'Har bir maqsad kaliti bor — lekin uni topish uchun harakat kerak. Xavotirlanish esa kalitni izlamaslik — faqat qulfdан qo\'rqish. Izlashni boshlang.', p:'Maqsadingizning "kaliti" nima deb o\'ylaysiz?' },
      { e:'🌙', t:'Tungi yo\'l qorong\'u ko\'rinadi — lekin mashinaning farasi yetarli. Siz hammani ko\'rishingiz shart emas — faqat keyingi qadamni ko\'rsangiz yetarli.', p:'Hozir ko\'rayotgan "keyingi qadam" nima?' },
      { e:'💫', t:'Maqsadlarsiz xavotir — ballon kabi. Ular maqsadga bog\'lanmasa — havo bilan uchadi. Xavotiringizni maqsadga yo\'naltiring.', p:'Xavotiringizni qaysi maqsadga yo\'naltira olasiz?' },
      { e:'🌊', t:'Daryoga qarshi suzib bo\'lmaydi — lekin oqim bilan suzsa, manzilga yetiladi. Maqsadingizga ham oqim topib eting — kuch sarflamay.', p:'Maqsadingizga borishning oson yo\'li qanday?' },
      { e:'🌿', t:'Organik o\'sish — sekin, lekin mustahkam. Tez natijalarga intilmang. Har kuni kichik va to\'g\'ri harakat — katta natija beradi.', p:'Bugun kichik lekin to\'g\'ri bitta harakat nima?' },
      { e:'⭐', t:'Yulduzlarga qarab yo\'l topiladi. Maqsadingiz — sizning yulduzingiz. Xavotir uni ko\'rishingizga xalaqit bermasin.', p:'Maqsadingiz siz uchun qaysi yulduz?' },
      { e:'🎯', t:'Nishonga urish uchun birinchi qadam — uni ko\'rish. Xavotir ko\'rishingizni bulamayapti. Ko\'zlaringizni yuming va nishonni ko\'ring.', p:'Nishonni aniq ko\'rganingizda nima his qilasiz?' },
      { e:'🌺', t:'Gul o\'sish uchun faqat suv va quyosh kerak — murakkab narsa emas. Maqsadingiz uchun ham — faqat harakat va sabr kerak. Murakkab emas.', p:'Maqsadingiz uchun hozir "suv va quyosh" nima?' },
    ],
    hard: [
      { e:'🌧️', t:'Xavotirlar ro\'yxatini yozing — hammasini. Qog\'ozda ko\'rsangiz, bosh ichidagi kabi katta bo\'lmaydi. Keyin qaysi biri bugun hal bo\'lishini belgilang.', p:'Barcha xavotirlaringizni yozing — hech birini qoldirmay.' },
      { e:'🕯️', t:'Qorong\'ida bitta sham yetarli. Hozir siz uchun "bir narsa" yetarli — hammasi emas. Faqat bu lahzani ko\'ring.', p:'"Hozir bitta narsa qilsam, bu nima bo\'lardi?" — yozing.' },
      { e:'🌊', t:'Xavotirni his qiling — lekin unda cho\'kmang. U to\'lqin kabi keladi va ketadi. Sen qirg\'oqsan — to\'lqin o\'tib ketadi.', p:'"Bu xavotir o\'tsa, nima his qilaman?" — yozing.' },
      { e:'🌿', t:'Aqa nima bilan bog\'liq ekanini bilib olsangiz — u zararini yo\'qotadi. Hozirgi xavotiringiz asli nimadan?', p:'Xavotiringizning ildizi nima?' },
      { e:'🌙', t:'Tunda xavotirlar kuchaygani — ular katta bo\'lganidan emas, jim bo\'lgani. Tun o\'tadi, kun chiqadi — va xavotirlar kichrayadi.', p:'Tun o\'tgandan keyin bu xavotir qanchalik katta bo\'ladi?' },
      { e:'🫶', t:'Xavotir — o\'zingizni himoya qilish instinkti. Unga rahmat ayting — lekin boshqarilish ruxsatini bermang. "Seni eshitdim, raxmat" deng va qo\'ying.', p:'Xavotiringizga "raxmat, lekin men boshqaraman" deng.' },
      { e:'🌸', t:'Gul bo\'rondan qo\'rqmaydi — chunki u ildiziga ishonadi. Siz ham o\'z "ildizingizga" ishoning — qiyin paytlarda u sizi tutib turadi.', p:'Sizning "ildizingiz" nima — sizni tutib turadigan narsa?' },
      { e:'🔮', t:'Xavotir ko\'pincha "va agar... bo\'lsa?" savolidan boshlanadi. O\'sha savolga javob yozing — eng yomoni nima, va uni hal qila olasizmi?', p:'"Eng yomoni bo\'lsa nima bo\'ladi?" — va keyin: "Buni hal qila olamanmi?"' },
      { e:'💜', t:'Xavotirli bo\'lish — kuchsizlik emas. Ko\'p kuchli va aqlli odamlar xavotirlanadi. Lekin ular xavotirni boshqarishni o\'rganadi.', p:'Xavotirni boshqarish uchun qanday usullaringiz bor?' },
      { e:'🌱', t:'Har bir qiyin payt — o\'sishning fursati. Xavotir sizni sinab ko\'ryapti — siz undan o\'tib chiqasiz va kuchliroq bo\'lasiz.', p:'Bu xavotirdan qanday kuch olasiz?' },
      { e:'🦅', t:'Burgut shamol bo\'lganda uchadi — shamolga qaramaydi, undan foydalanadi. Xavotirni ham shu tarzda ishlating — to\'siq emas, qanot.', p:'Xavotiringizni qanday "qanot" ga aylantirish mumkin?' },
      { e:'🌈', t:'Kamalak yomg\'irdan keyin chiqadi. Siz hozir yomg\'ir ichida bo\'lishingiz mumkin — lekin kamalak kutmoqda. Sabr qiling.', p:'Bu xavotirdan keyin qanday "kamalak" chiqadi?' },
    ],
    creative: [
      { e:'🎨', t:'Ijod — xavotirning eng yaxshi dorisi! Qo\'lingizga biror narsa oling: bo\'yoq, qalam, yoki klaviatura. Hissiyotlaringizni chiqarib tashlang — baholash kerak emas.', p:'Xavotiringizni rasm yoki so\'z bilan ifodalang.' },
      { e:'🖊️', t:'Yozing — hamma narsani, tartibsiz. Bosh ichidagi fikrlarni qog\'ozga to\'kib soling. Bu "brain dump" — eng yaxshi terapiya.', p:'5 daqiqa to\'xtovsiz yozing — nima kelsa.' },
      { e:'🎵', t:'Musiqa — tinchlantiradi. Hozir quloqchinni takib, sevimli qo\'shig\'ingizni eshiting. Hech narsa qilmasdan, faqat eshiting — nafas oling.', p:'Tinchlanadigan qo\'shig\'ingiz bormi? Uning nomini yozing.' },
      { e:'🌊', t:'Ijod — xavotirni chiqarish yo\'li. Uni qog\'ozga "to\'kib" tashlang — u qog\'ozda qoladi, siz esa ozod bo\'lasiz.', p:'Xavotiringizni qog\'ozga "to\'kib" tashlang.' },
      { e:'🎭', t:'Ba\'zan xavotirni "rol" sifatida ko\'rish yordam beradi. "Xavotirli men" rolini bir chetga qo\'yib, "kuchli men" rolini o\'ynasangiz?', p:'"Kuchli men" qanday harakat qiladi?' },
      { e:'🌸', t:'Gul chizish — xavotirni kamaytiradi. Bu ilmiy isbotlangan. Hozir oddiy gul chizing — rangli, chiroyli. Faqat chizing, fikrlamang.', p:'5 daqiqa gul chizing — natijasi muhim emas.' },
      { e:'💡', t:'Ijodiy fikrlash — xavotirdan ijodiy yechim topishdir. Muammoingizni ijodiy hal qilish uchun qanday g\'oya bormi?', p:'Xavotiringizning ijodiy yechimi nima bo\'lishi mumkin?' },
      { e:'📸', t:'Go\'zallik izlash — xavotirni kamaytiradi. Atrofingizda go\'zal bir narsa toping va suratga oling yoki tasvirlab yozing.', p:'Hozir atrofingizda qanday go\'zallik bor?' },
      { e:'🌿', t:'Tabiatga chizish — eng qadimiy meditatsiya. Daraxt, gul, tog\' — nima bo\'lsa, chizing. Tabiat — tinchlik beradi.', p:'Tabiatda qaysi narsani chizmoqchisiz?' },
      { e:'🔮', t:'Tasavvur qiling: xavotirsiz siz nima yaratardi? O\'sha narsani yarating — go\'yo xavotir yo\'q deb. Ijod siz uchun ozodlik.', p:'Xavotirsiz siz nima yaratardingiz?' },
      { e:'🎀', t:'Ba\'zan biror narsani qo\'l bilan ishlash — xavotirni tindiradi. Munchoq tirish, rasm bo\'yash, gul ekish — qo\'llaringiz band bo\'lsin.', p:'Qo\'llaring bilan nima qilsangiz tinchlashis?' },
      { e:'🌈', t:'Xavotirli ranglarin o\'zgartirsangiz? Qora-kulrang o\'rniga yorqin ranglar bilan chizib ko\'ring. Ranglar kayfiyatni o\'zgartiradi.', p:'Xavotiringizni yorqin rangda ifodalasangiz qanday ko\'rinardi?' },
    ],
    relation: [
      { e:'💬', t:'Munosabatlardagi xavotir ko\'pincha bitta samimiy suhbat bilan yechiladi. Ichingizda saqlagan narsani — shu odamga ayting. Qo\'rqsangiz ham.', p:'Kimga biror narsani aytishdan qo\'rqayapsiz?' },
      { e:'🤗', t:'O\'zingizni himoya qilish uchun atrofingizga devol qurmang. Ba\'zan kuchsizligingizni ko\'rsatish — eng kuchli ish.', p:'"Kimga ishonaman?" — yozing.' },
      { e:'🌸', t:'Hamma munosabat mukammal emas — bu normal. Xavotirlaringizni yozib, keyin qaysi biri haqiqiy ekanini ajrating.', p:'Munosabatlarda sizni bezovta qiladigan narsa nima?' },
      { e:'🌙', t:'Yolg\'izlik xavotiri — bu siz muhim ekanligingiz va sevgi istayotganligingizning belgisi. Bu yaxshi narsa. Lekin bitta qadam qo\'ying — birovga yozing.', p:'Kimga yozasiz bugun?' },
      { e:'💌', t:'Xabar yozish — oddiy, lekin kuchli. "O\'ylayotib eding" deb yozish ham yetarli. Siz qanchalik ko\'p o\'ylaganingizni odamlar bilishmaydi.', p:'Hozir kimni o\'ylayapsiz? Unga yozing.' },
      { e:'🌿', t:'Munosabatlarda xavotir ba\'zan — haddan ortiq tahlildan. Ba\'zan shunchaki his qilib, his qildirish yetarli. Tahlilni to\'xtating, his qiling.', p:'Bu munosabatda siz nima his qilyapsiz?' },
      { e:'🫂', t:'Ba\'zan birovning yonida o\'tirish — eng yaxshi dori. So\'z kerak emas. Hozir kimning yoniga borishingiz mumkin?', p:'Kim bilan shunchaki yonida o\'tirishingiz mumkin?' },
      { e:'🌷', t:'Xavotirli odamlar ko\'pincha boshqalar haqida ortiq o\'ylaydi — o\'zini unutib. O\'zingizga ham e\'tibor bering — siz ham muhimsiz.', p:'O\'zingizga e\'tibor berish uchun bugun nima qilasiz?' },
      { e:'💫', t:'Munosabatlardagi xavotir — sevgi belgisi. Agar sevmasangiz — xavotirlanmaydi edingiz. Shu xavotirni sevgiga aylantiring.', p:'Bu xavotiringizni sevgiga qanday aylantira olasiz?' },
      { e:'🌊', t:'Munosabatlar — ikkala tomon oqimi. Siz juda ko\'p "bering", kam "oling" bo\'layapsizmi? Balansni qarang.', p:'Munosabatlarda balans bormi?' },
      { e:'🌸', t:'Odamlarni ko\'p o\'ylab, o\'zingizni unutib qo\'ygansizmi? Birinchi o\'zingizga qayting — so\'ng atrofingizgа.', p:'O\'zingizga qayish uchun nima qilasiz?' },
      { e:'🎀', t:'Munosabatlardagi xavotir ko\'pincha "ular meni qanday ko\'radi" savolidan. Ammo muhimroq savol — "men o\'zimni qanday ko\'raman?"', p:'"Men o\'zimni qanday ko\'raman?" — yozing.' },
    ],
  },

  searching: {
    self: [
      { e:'🔭', t:'Izlash — o\'sishning eng kuchli belgisi! Siz kim bo\'lmoqchi ekanligingizni qidiryapsiz — bu juda katta ish. Javoblar sekin keladi, lekin siz to\'g\'ri yo\'ldasiz.', p:'"Men qanday odam bo\'lmoqchiman?" — erkin yozing.' },
      { e:'🌀', t:'Ba\'zan o\'zimizni yo\'qotib qo\'yamiz — bu yangi o\'zimizni topish uchun. Eski siz o\'tayapti, yangi siz kelayapti. Qo\'rqmang.', p:'"5 yil oldingi men va hozirgi men — qanday farq bor?" yozing.' },
      { e:'🗺️', t:'Hayot — xaritasiz sayohat. Hamma ham yo\'lini bilmay yuradi — faqat ba\'zilar buni yashiradi. Siz kamida izlayapsiz — bu juda katta qadam.', p:'"Kim bo\'lmoqchi emasman?" — bu ham javob. Yozing.' },
      { e:'🌱', t:'O\'zingizni topish — hayotiy ish. Bu bir kunda tugamaydi — lekin har kuni biroz aniqroq bo\'ladi. Bugun qaysi bir aniqlikka erishdingiz?', p:'Bugun o\'zingiz haqida nima yangi bildingiz?' },
      { e:'🔮', t:'O\'z-o\'zini bilish — eng qadimiy falsafa. "O\'z-o\'zingni bil" — ming yillik hikmat. Siz hozir shu yo\'ldasiz. Bu yo\'l cheksiz va go\'zal.', p:'O\'zingiz haqida eng sirli narsa nima?' },
      { e:'🌙', t:'Qorong\'uda ko\'proq narsa ko\'rinadi — ko\'zlar moslashadi. Siz hozir "qorong\'uda" — ammo shunday ko\'proq ko\'rmoqdasiz.', p:'Hozirgi holatda nima yangi ko\'rayapsiz?' },
      { e:'💫', t:'Ba\'zan biz o\'zimizni atrof ko\'zgusida ko\'ramiz — boshqalar orqali. Qaysi odamning siz haqingizda aytgan gapi sizga ta\'sir qildi?', p:'Kimning qaysi gapi sizni chuqur o\'ylantirdi?' },
      { e:'🌸', t:'Gul qaysi rangda ochilar ekanligini bilmaydi — u faqat o\'sadi. Siz ham shunday — o\'sing, qaysi rang chiqishini ko\'ring.', p:'O\'sib borish jarayonida nima kashf qilmoqdasiz?' },
      { e:'🌊', t:'Dengiz qaysi qirg\'oqqa yetishini bilmaydi — u faqat oqadi. Siz ham o\'z oqimingizga ishoning — u to\'g\'ri joyga olib boradi.', p:'O\'z oqimingizga ishonasizmi?' },
      { e:'🦋', t:'Kapalak qurtlikdan kapalagiga o\'tish — eng chuqur o\'zgarish. Siz hozir shu jarayondasiz. Qurt bo\'lish — kamchilik emas, tayyorlanish.', p:'Qaysi "pilla" ichida ekanligingizni his qilyapsiz?' },
      { e:'🔍', t:'O\'zingizni qidirish — hayotning eng jiddiy ishi. Ko\'pchilik bu ishni umuman qilmaydi. Siz uni qilyapsiz — bu imtiyoz.', p:'"O\'zim" deb qanday narsani tushunasiz?' },
      { e:'⭐', t:'Hamma yulduz o\'z nuriga ega — boshqasiga o\'xshab nurlana olmaydi. Sizning nuringiz ham o\'zgacha — uni toping.', p:'Sizning o\'ziga xos "nuringiz" nima deb o\'ylaysiz?' },
    ],
    goals: [
      { e:'🌱', t:'Maqsad yo\'q deb o\'ylasangiz — aslida izlayapsiz. Izlash ham yo\'nalish. Hozir qaysi sohada o\'rganish, sinab ko\'rish qiziq? O\'shandan boshlang.', p:'Hayotda nima sizni qiziqtiradi? Ro\'yxat tuzing.' },
      { e:'🔑', t:'Maqsadlar ba\'zan topiladi — qidirilmaydi. Ko\'proq tajriba yig\'ing: yangi narsa o\'rganing, yangi joy boring, yangi odam bilan gaplashing.', p:'Bu oy bitta yangi narsani sinab ko\'rasiz — nima bo\'ladi?' },
      { e:'💡', t:'Maqsadsiz his qilish — boshi bo\'sh maydon. U — imkoniyat. Hech qanday cheklovlarsiz — nima qilmoqchi edingiz?', p:'"Agar hech kim bilmasa nima qilardim?" — yozing.' },
      { e:'🌊', t:'Dengiz har qirg\'oqni kashf qiladi — tinimsiz. Siz ham tinmayin. Har bir yangi tajriba — maqsadingizga yaqinlashtirgandek.', p:'Qaysi yangi tajribani izlayapsiz?' },
      { e:'🧭', t:'Yo\'nalish topish uchun birinchi — qayerga bormoqchi emasligingizni bilish kerak. Siz uchun "yo\'q" nimasiz?', p:'Hayotda nima sizga mos emas?' },
      { e:'🌸', t:'Ba\'zan maqsad — bu emas deb belgilab boriladi. "Bu men uchun emas" har bir narsa — to\'g\'ri narsaga yaqinlashtiadi.', p:'"Bu men uchun emas" deb qaysi narsani tugatdingiz?' },
      { e:'🎯', t:'O\'xchilar ham dastlab nishonni qidiradi — keyin uradi. Siz hozir nishon qidirish bosqichadasiz. Bu normal va muhim.', p:'Qanday nishon izlayapsiz?' },
      { e:'🌿', t:'Organik o\'sish shoshilmaydi. Siz hozir o\'z yo\'lingizni o\'rganayapsiz. Bu jarayon vaqt oladi — lekin natija aniq bo\'ladi.', p:'Bu izlanish jarayonida nima topmoqdasiz?' },
      { e:'🌙', t:'Yulduzlar navbatma-navbat ko\'rinadi — hamma birdan emas. Maqsadlaringiz ham shunday — asta-sekin oydinlashadi.', p:'Hozir qaysi maqsad biroz aniq ko\'rinyapti?' },
      { e:'💫', t:'Izlanish — eng qimmatli jarayon. Ko\'pchilik topib qo\'yib, izlanishni to\'xtatadi. Siz hali topmoqdasiz — bu ajoyib.', p:'Izlanish jarayoni sizga nima beradi?' },
      { e:'🔮', t:'Kelajakni bilmaslik — bu yomon emas. Bu imkoniyatlar ko\'p ekanligini bildiradi. Har bir yo\'l yopilmagan.', p:'Kelajak noma\'lumligi sizni qo\'rqitiradimi yoki hayajonlantiradimi?' },
      { e:'🌈', t:'Hayot — bir yo\'nalishdan iborat emas. Ko\'p marta burilish mumkin. Hozirgi yo\'l noto\'g\'ri ko\'rinsa — burilish mumkin.', p:'Qaysi yo\'lni sinab ko\'rmoqchisiz?' },
    ],
    hard: [
      { e:'🌫️', t:'Qidirish — ko\'pincha og\'riqli. Lekin bu og\'riq — sizni to\'g\'ri joyga olib bormoqda. Yo\'lni bilmaslik — noto\'g\'ri yurish emas.', p:'"Bu qiyinchilik meni qaerga olib bormoqda?" — yozing.' },
      { e:'🌙', t:'Qorong\'uda yulduzlar ko\'rinadi. Siz hozir qorong\'uda — lekin shuning uchun ham ichki yulduzlaringizni ko\'ra olasiz.', p:'Qiyin paytlarda o\'zingizdan nima topgansiz?' },
      { e:'🔥', t:'Yo\'qolish — ba\'zan topilish uchun kerak bo\'ladi. Siz hozir o\'z o\'tchangdan o\'tayapsiz — narigi tomonda yangi siz bor.', p:'"Bu qiyinchilik tugagach, men qanday odam bo\'laman?" — yozing.' },
      { e:'🌊', t:'Dengiz pastki oqimida ko\'p narsalar bor — yuzadan ko\'rinmaydi. Siz ham hozir chuqur qatlaming izlayapsiz. Bu daraja — ko\'pchilikka nasib etmaydi.', p:'O\'zingizning chuqur qatlamlaringizda nima bor?' },
      { e:'🌸', t:'Gul qish o\'tgach ochiladi — lekin qish davomida ildiz mustahkamlanadi. Siz hozir ildiz mustahkamlanayapti.', p:'Bu davrda qanday ildiz qo\'yayapsiz?' },
      { e:'🌿', t:'Izlash yo\'lida qiyinchilik — to\'siq emas, tekshiruv. "Bu yo\'l menikicha?" degan savol. Javob — davom etish yoki burilish.', p:'Bu yo\'l siznikimi deb his qilyapsizmi?' },
      { e:'💎', t:'Olmosni topish uchun qazish kerak — qiyinchiliklarsiz emas. Siz hozir qazayapsiz. Olmosni topasiz.', p:'Qaysi "olmosni" qidirmoqdasiz?' },
      { e:'🌙', t:'Hamma ulug\' odamlar yo\'qolgan davr o\'tkazgan — so\'ng topilgan. Siz o\'sha davrdasiz. Shoshilmang.', p:'Bu yo\'qolish davri sizga nima beradi?' },
      { e:'🦅', t:'Burgut uchishni birinchi urinishda bilmagan — yiqilgan, qaytadan uringan. Siz ham shunday — yiqilish ham yo\'lning bir qismi.', p:'Yiqilishdan nima o\'rgandingiz?' },
      { e:'🌱', t:'Urug\' unib chiqishdan oldin qorong\'u tuproq ostida bo\'ladi. Siz hozir shu tuproq ostidasi — lekin o\'sish boshlanib bo\'lgan.', p:'O\'sish boshlanganing belgisi nima?' },
      { e:'🌈', t:'Kamalak ko\'rinishi uchun ham quyosh, ham yomg\'ir kerak. Siz hozir yomg\'ir ichida — quyosh ham bor.', p:'Hayotingizda hozir qaysi quyosh bor?' },
      { e:'🔮', t:'Ba\'zan yo\'l — manzilga yetganingizdan keyin ko\'rinadi. Hozir ko\'rinmasa ham — u bor. Davom eting.', p:'Davom etishga kuch qayerdan olasiz?' },
    ],
    creative: [
      { e:'🎭', t:'Ijod — o\'zingni topishning eng qadimiy usuli. Bir narsa yarating — nima bo\'lsa ham. Undan o\'zingiz haqingizda biror narsa bilib olasiz.', p:'Biror narsani yarating va "bu menga nima aytadi?" deb so\'rang.' },
      { e:'✏️', t:'Hamma narsani yozib chiqing — savollar, shubhalar, orzular. Qog\'oz — eng yaxshi terapeving. U hukm qilmaydi, faqat eshitadi.', p:'10 daqiqa to\'xtovsiz — ichingizda nima bo\'lsa yozing.' },
      { e:'🌈', t:'Ba\'zan biz o\'zimizni ijod orqali topamiz — mantiq orqali emas. Bugun biror narsani yarating va u sizga kim ekanligingizni ko\'rsatsin.', p:'"Men yaratayotganda kim bo\'laman?" — yozing.' },
      { e:'🎨', t:'Izlanayotgan odamlar eng chuqur ijod qiladi — chunki hali hamma narsa ochiq. Siz bugun qog\'oz boshida turgan odamsiz — unga hamma narsa yozing.', p:'Bo\'sh qog\'ozga birinchi nima chiqqan?' },
      { e:'🌊', t:'Dengiz — ko\'p yo\'nalishga oqadi. Ijod ham shunday — qaysi tomonga oqish istaysiz? Bugun sinab ko\'ring.', p:'Yangi ijodiy yo\'nalishni sinab ko\'rasizmi?' },
      { e:'💡', t:'G\'oyalar siz izlayotgan javoblarni beradi — lekin faqat g\'oyalaringizni chiqarganingizda. Qog\'ozga hamma g\'oyangizni to\'king.', p:'Hozir qanday g\'oyalar bor miyangizda?' },
      { e:'🎵', t:'Musiqa — eng universal til. Bugun biror yangi janr eshiting — tanish bo\'lmagan. Kutilmagan narsa kutilmagan his beradi.', p:'Qaysi musiqa janrini hech eshitmagan bo\'lsangiz ham eshitasiz?' },
      { e:'🌸', t:'Ijod — o\'yinning kattalarga mo\'ljallangan versiyasi. Bugun faqat o\'yin uchun biror narsa yarating — natija muhim emas.', p:'Faqat quvonch uchun nima yaratardingiz?' },
      { e:'📖', t:'Boshqa odamlarning hayotini o\'qish — o\'z hayotingizni tushunishga yordam beradi. Bugun biror kitob yoki maqola o\'qing.', p:'Qaysi kitob siz haqingizda ko\'p narsa aytdi?' },
      { e:'🖌️', t:'Chizish — so\'zsiz til. Hozir qog\'ozga chizgin — nima chiqsa. So\'ngra "bu nima haqida?" deb so\'ra. Javob sizni ajablantirishi mumkin.', p:'Tasodifiy chizgin — keyin izoh yoz.' },
      { e:'🌿', t:'Tabiatda o\'tirish va kuzatish — ijodiy fikrlar olib keladi. Bugun tashqariga chiqin va faqat kuzating. Hech narsa qilmasdan.', p:'Tabiatda nima ko\'rgan bo\'lsangiz, yozing.' },
      { e:'🔮', t:'Ijod — kelajakka xat yozish. Bugun 5 yil keyingi o\'zingizga xat yozing. U qanday hayot kechiryapti?', p:'5 yil keyingi o\'zingizga xat yozing.' },
    ],
    relation: [
      { e:'🌐', t:'O\'zingizni munosabatlarda yo\'qotdingizmi? Bu ko\'pchilikka tanish. Kim siz bo\'lmasangiz ham — aniqlash vaqti. Qaysi munosabatda o\'zingiz emassiz?', p:'"Qaysi munosabatlarda o\'zimman?" — yozing.' },
      { e:'🤲', t:'O\'zingizga mos odamlarni topish — hayotning eng katta topilmasi. Siz izlayapsiz — demak siz uchun joy bor. Shoshma.', p:'Qaysi odamlar bilan bo\'lganda eng o\'zingiz bo\'lasiz?' },
      { e:'💞', t:'Chuqur munosabatlar — o\'z-o\'zingizni bilganingizda boshlanadi. Hozir siz shu ish bilan band — bu munosabatlarga tayyorlanish.', p:'"Meni haqiqatan tushungan odam men haqimda nima derdi?" — yozing.' },
      { e:'🌸', t:'Ba\'zan biz o\'zimizga mos odamlarni topishdan qo\'rqamiz — chunki o\'zingizni bilmasangiz, nimani qidirganingizni ham bilmaysiz. Avval o\'zingizni biling.', p:'Munosabatda siz uchun eng muhim narsa nima?' },
      { e:'🌙', t:'Yolg\'iz vaqt — o\'zingiz bilan tanishish vaqti. Bu davrni qadrlay oling. Izlayotganingizda yolg\'iz bo\'lish — zarur qism.', p:'Yolg\'iz vaqtda o\'zingiz haqida nima bilyapsiz?' },
      { e:'🌊', t:'Har bir munosabat sizga biror narsa o\'rgatadi — hatto og\'riqlisi ham. Hozirgi yoki o\'tgan munosabatdan nima o\'rgandingiz?', p:'Munosabatlardan o\'rgangan eng muhim dars nima?' },
      { e:'🌿', t:'O\'z-o\'zingizni topish jarayonida munosabatlar o\'zgaradi — ba\'zilar qoladi, ba\'zilari ketadi. Bu — tabiiy. Haqiqiy ulanishlar qoladi.', p:'Hayotingizda qaysi odamlar "haqiqiy" ulanish beradi?' },
      { e:'💫', t:'Siz hali o\'zingizni to\'liq topmaganmiz — bu munosabatlarga ham ta\'sir qiladi. Lekin bu jarayon — sizni chuqurroq odamga aylantiradi.', p:'O\'sish jarayoni munosabatlaringizni qanday o\'zgartirdi?' },
      { e:'🎀', t:'O\'zingizni sevishni o\'rganish — eng go\'zal sovg\'a, ham o\'zingizga, ham boshqalarga. Bu o\'rganish hozir davom etmoqda.', p:'O\'zingizni sevishni o\'rganish jarayonida nimalar bo\'lyapti?' },
      { e:'🌷', t:'Ba\'zan eng yaxshi munosabat — o\'zingiz bilan. O\'zingizga yaxshi do\'st bo\'lishni o\'rganing — boshqalar ham shunday do\'st bo\'ladi.', p:'O\'zingizga qanday do\'st bo\'lyapsiz?' },
      { e:'🔮', t:'Hayotingizda qaysi odamlar sizni o\'zingiz bo\'lishga ilhomlantiradi? Ularni qadrlab, ko\'proq vaqt o\'tkazing.', p:'Sizni o\'zingiz bo\'lishga ilhomlantiruvchi kim?' },
      { e:'🌈', t:'Turli xil odamlar — turli xil ko\'zgular. Ularning har biri sizga o\'zingizning biror qirrangizni ko\'rsatadi. Kim sizning qaysi qirangingizni ko\'rsatdi?', p:'Kim siz haqida siz bilmagan narsani ko\'rsatdi?' },
    ],
  },
};
